function contractTrigger=NewContractTriggers(Dates)
contractTrigger=timetable(...
    'VariableNames',...
    {'Marked','ThDiffVolMax','ThDiffVolAve','ThVol',...
    'ThMaxHigh','ThEntryStp','ThEntryLmt','ThMAtr',...
    'ThTarget','ThTarget1','ThTarget2','ThStpLmtDiffPerc'});
end