
annualinflationrate=0.08;

basedir='Z:\My files\Project trading\traderdata\data\';
processdir='Z:\My files\Project trading\traderdata\data_processed\dailytrendprofile\';
date0=datestr(datetime()-days(1),'yyyy-mm-dd');
pdirlast = [processdir date0 '\'];
    if (~exist(pdirlast))
    mkdir(pdirlast);
    end
    
contracts_yahoo;
contracts_main;
ncontracts=numel(contracts);

for ci=1:ncontracts
symbol=contracts{ci}.FileSymbol;
disp(symbol);
trendprofiflename=[pdirlast 'PDTP1 ' symbol ' ID' '3' '.mat'];

if (exist(trendprofiflename)==0)

try
fn=[basedir symbol '\' symbol ' daily 5y ' date0 '.mat'];load(fn);
params.TimeTables.Day=table2timetable(td);

sub_dailytrendprocess;

conditions={'premarketdn','gapdn','gapunderlow','trenddn','lastcandlesdn','strategy_bearish','dsma200<inflationrate','dsma100<inflationrate',...
    'dsma50<inflationrate','(sma100<sma200)','sma50<sma200',...
    'shiftpad(lastdcandles,1)<inflationrate','shiftpad(lastdcandles,2)<inflationrate','shiftpad(lastdcandles,3)<inflationrate',...
    'shiftpad(lastdcandles,4)<inflationrate',...
    'shiftpad(lastdcandles,1)<inflationrate & shiftpad(lastdcandles,1)>-1*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,1)>-1*atrthresh1+inflationrate','shiftpad(lastdcandles,1)<-1*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,1)>-2*atrthresh1+inflationrate','shiftpad(lastdcandles,1)<-2*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,1)>-4*atrthresh1+inflationrate','shiftpad(lastdcandles,1)<-4*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,2)>inflationrate | shiftpad(lastdcandles,3)>inflationrate |shiftpad(lastdcandles,4)>inflationrate',...
    'strategy_superposition_main_bearish>4','strategy_superposition_main_bearish>5',...
    'shiftpad(lastdcandles,1)>-4*atrthresh1+inflationrate & shiftpad(lastdcandles,1)<-2*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,1)>-2*atrthresh1+inflationrate & shiftpad(lastdcandles,1)<0*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,1)>-1*atrthresh1+inflationrate & shiftpad(lastdcandles,1)<1*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,1)> 2*atrthresh1+inflationrate & shiftpad(lastdcandles,1)<4*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,2)>-4*atrthresh1+inflationrate & shiftpad(lastdcandles,2)<-2*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,2)>-1*atrthresh1+inflationrate & shiftpad(lastdcandles,2)<1*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,2)>-2*atrthresh1+inflationrate & shiftpad(lastdcandles,2)<4*atrthresh1+inflationrate',...
    'premarketup','gapup','gapoverhigh','trendup','lastcandlesup','strategy_bullish','dsma200>inflationrate','dsma100>inflationrate',...
    'dsma50>inflationrate','(sma100>sma200)','sma50>sma200','dsma200<inflationrate','dsma100<inflationrate',...
    'shiftpad(lastdcandles,1)>inflationrate','shiftpad(lastdcandles,2)>inflationrate','shiftpad(lastdcandles,3)>inflationrate',...
    'shiftpad(lastdcandles,4)>inflationrate',...
    'shiftpad(lastdcandles,1)>inflationrate & shiftpad(lastdcandles,1)<1*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,1)>1*atrthresh1+inflationrate','shiftpad(lastdcandles,1)<1*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,1)>2*atrthresh1+inflationrate','shiftpad(lastdcandles,1)<2*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,1)>4*atrthresh1+inflationrate','shiftpad(lastdcandles,1)<4*atrthresh1+inflationrate',...
    'shiftpad(lastdcandles,2)<inflationrate | shiftpad(lastdcandles,3)<inflationrate |shiftpad(lastdcandles,4)<inflationrate',...
    'strategy_superposition_main_bullish>4','strategy_superposition_main_bullish>5',...
    'fullgapup','fullgapdn',...
    };
nc=numel(conditions);

probabilities=zeros(2,floor(nc+nc*nc/2+nc*nc*nc/4));
cdayss=zeros(2,floor(nc+nc*nc/2+nc*nc*nc/4));
conditionnames=cell(1,floor(nc+nc*nc/2+nc*nc*nc/4));

direction=dndays;
dirtext='bearish';
allindex=1;

sub_dailytrendevaluation;
%sub_dailytrendplot;

direction=updays;
dirtext='bullish';
allindex=2;

sub_dailytrendevaluation;
%sub_dailytrendplot;



save(trendprofiflename,'allgoodconditions','probabilities','cdayss');
catch exception
   dumpReport('error.log', exception);

end
else
disp('already exists');

end
end