<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IB\OrderDefinition\IBControlDefinition.csproj" />
    <ProjectReference Include="..\..\temp TWS API\source\CSharpClient\client\CSharpAPI.csproj" />
    <ProjectReference Include="..\ContractDefinition\ContractDefinition.csproj" />
    <ProjectReference Include="..\IBAccountDefinition\IBAccountDefinition.csproj" />
    <ProjectReference Include="..\IBBackEnd\IBBackEnd.csproj" />
    <ProjectReference Include="..\IBWrapper\IBWrapper.csproj" />
    <ProjectReference Include="..\OrderDefinition_\OrderDefinition.csproj" />
    <ProjectReference Include="..\SystemExtension\SystemExtension.csproj" />
    <ProjectReference Include="..\TradeExtensionExternalCondtion\TradeExtension.csproj" />
  </ItemGroup>

</Project>