% Solve an Input-Output Time-Series Problem with a Time Delay Neural Network
% Script generated by Neural Time Series app.
% Created 01-Jun-2020 22:25:58
%
% This script assumes these variables are defined:
%
%   pollutionInputs - input time series.
%   pollutionTargets - target time series.

load('sample.mat');

%fix the causality of the data

predictmanysamples=10;

targetindex=4;

attmc=attm((predictmanysamples+1):end,targetindex);

%just for understaing that T is not needed in prediction
attmx=zeros(size(attm((predictmanysamples+1):end,targetindex)));
mx=tonndata(attmx,false,false);

attmx_=attm(1:end-predictmanysamples,:);

X = tonndata(attmx_,false,false);
T = tonndata(attmc,false,false);

x=X{1};
x(2)=nan;
X{1}=x;
% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainlm';  % Levenberg-Marquardt backpropagation.

% Create a Time Delay Network
inputDelays = 1:5;
hiddenLayerSize = 10;
net = timedelaynet(inputDelays,hiddenLayerSize,trainFcn);

% Choose Input and Output Pre/Post-Processing Functions
% For a list of all processing functions type: help nnprocess
net.input.processFcns = {'removeconstantrows','mapminmax'};
net.output.processFcns = {'removeconstantrows','mapminmax'};

% Prepare the Data for Training and Simulation
% The function PREPARETS prepares timeseries data for a particular network,
% shifting time by the minimum amount to fill input states and layer
% states. Using PREPARETS allows you to keep your original time series data
% unchanged, while easily customizing it for networks with differing
% numbers of delays, with open loop or closed loop feedback modes.
[x,xi,ai,t] = preparets(net,X,T);

% Setup Division of Data for Training, Validation, Testing
% For a list of all data division functions type: help nndivision
net.divideFcn = 'dividerand';  % Divide data randomly
net.divideMode = 'time';  % Divide up every sample
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Choose a Performance Function
% For a list of all performance functions type: help nnperformance
net.performFcn = 'mse';  % Mean Squared Error

% Choose Plot Functions
% For a list of all plot functions type: help nnplot
net.plotFcns = {'plotperform','plottrainstate', 'ploterrhist', ...
    'plotregression', 'plotresponse', 'ploterrcorr', 'plotinerrcorr'};

% Train the Network
[net,tr] = train(net,x,t,xi,ai);

% Test the Network
y = net(x,xi,ai);
e = gsubtract(t,y);
performance = perform(net,t,y)

% Recalculate Training, Validation and Test Performance
trainTargets = gmultiply(t,tr.trainMask);
valTargets = gmultiply(t,tr.valMask);
testTargets = gmultiply(t,tr.testMask);
trainPerformance = perform(net,trainTargets,y)
valPerformance = perform(net,valTargets,y)
testPerformance = perform(net,testTargets,y)

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotresponse(t,y)
%figure, ploterrcorr(e)
%figure, plotinerrcorr(x,e)

% Step-Ahead Prediction Network
% For some applications it helps to get the prediction a timestep early.
% The original network returns predicted y(t+1) at the same time it is
% given x(t+1). For some applications such as decision making, it would
% help to have predicted y(t+1) once x(t) is available, but before the
% actual y(t+1) occurs. The network can be made to return its output a
% timestep early by removing one delay so that its minimal tap delay is now
% 0 instead of 1. The new network returns the same outputs as the original
% network, but outputs are shifted left one timestep.
nets = removedelay(net);
nets.name = [net.name ' - Predict One Step Ahead'];
view(nets)
[xs,xis,ais,ts] = preparets(nets,X,T);
ys = nets(xs,xis,ais);
stepAheadPerformance = perform(nets,ts,ys)

% Deployment
% Change the (false) values to (true) to enable the following code blocks.
% See the help for each generation function for more information.
if (false)
    % Generate MATLAB function for neural network for application
    % deployment in MATLAB scripts or with MATLAB Compiler and Builder
    % tools, or simply to examine the calculations your trained neural
    % network performs.
    genFunction(net,'myNeuralNetworkFunction');
    y = myNeuralNetworkFunction(x,xi,ai);
end
if (false)
    % Generate a matrix-only MATLAB function for neural network code
    % generation with MATLAB Coder tools.
    genFunction(net,'myNeuralNetworkFunction','MatrixOnly','yes');
    x1 = cell2mat(x(1,:));
    xi1 = cell2mat(xi(1,:));
    y = myNeuralNetworkFunction(x1,xi1);
end
if (false)
    % Generate a Simulink diagram for simulation or deployment with.
    % Simulink Coder tools.
    gensim(net);
end


%purpose of prediction)
samplesizediff=inputDelays(end);+predictmanysamples;
range=1:size(X,2);
xx=X(range);
tt=mx(range);%this doesn't matter... it may as well be any data with that structure
%try mx instead of T, which is a different column of data
[xs,xis,ais,ts] = preparets(nets,xx,tt);
ys = nets(xs,xis,ais);

xxm=cell2mat(xx);
ysm=cell2mat(ys);
for i=1:size(ysm,1)
figure
hold on;
title('prediction when it is available, predictmanysamples ahead of itme');

plot(1:numel(xxm(2,:)),xxm(2,:),'g');
plot(1:numel(xxm(4,:)),xxm(4,:),'b');
plot(1:numel(xxm(3,:)),xxm(3,:),'r');
plot((1:numel(ysm(i,:)))+samplesizediff,ysm(i,:),'k--');
end


%purpose of prediction)
samplesizediff=inputDelays(end)+predictmanysamples;
range=1:size(X,2);
xx=X(range);
tt=mx(range);%this doesn't matter... it may as well be any data with that structure
%try mx instead of T, which is a different column of data
[xs,xis,ais,ts] = preparets(nets,xx,tt);
ys = nets(xs,xis,ais);

xxm=cell2mat(xx);
ysm=cell2mat(ys);
for i=1:size(ysm,1)
figure
hold on;
title('prediction when it happens');

plot(1:numel(xxm(2,:)),xxm(2,:),'g');
plot(1:numel(xxm(4,:)),xxm(4,:),'b');
plot(1:numel(xxm(3,:)),xxm(3,:),'r');
plot((1:numel(ysm(i,:)))+samplesizediff,ysm(i,:),'k--');
end