<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IB\OrderDefinition\IBControlDefinition.csproj" />
    <ProjectReference Include="..\..\temp TWS API\source\CSharpClient\client\CSharpAPI.csproj" />
    <ProjectReference Include="..\ContractDefinition\ContractDefinition.csproj" />
    <ProjectReference Include="..\IBBackEnd\IBBackEnd.csproj" />
    <ProjectReference Include="..\OrderDefinition_\OrderDefinition.csproj" />
  </ItemGroup>

</Project>
