contracts={
%genContract([],'AAPL'),...
genContract([],'LOW'),...
genContract([],'GOLD'),...%GOLD
genContract([],'SLV'),... %SILVER ETF
genContract([],'FB'),... %SOCIAL MEDIA
genContract([],'DAL'),... % TRANSPOT/SHIPPING
genContract([],'AAL'),...
genContract([],'FDX'),...
genContract([],'UPS'),...
genContract([],'UAL'),...
genContract([],'AMZN'),...% INTERNET/ECOMMERCE
genContract([],'NFLX'),...
genContract([],'INTC'),... %SEMICONDUCTOR
genContract([],'JPM'),...
genContract([],'V'),...
genContract([],'WMT'),... %END OF RETAIL
genContract([],'ROKU'),...
genContract([],'DGLY'),...
genContract([],'AIM'),...
genContract([],'ZM'),...
genContract([],'UBER'),...
genContract([],'AMD'),...
genContract([],'NVDA'),...
genContract([],'DOCU'),...
genContract([],'DIS'),...
genContract([],'GOOG'),...
genContract([],'KO'),...
genContract([],'BABA'),...
genContract([],'FSLY'),...
genContract([],'QCOM'),...
genContract([],'SBUX'),...
genContract([],'MMM')...
};

% contracts={
% 	genContract([],'AAL'),...
%     genContract([],'AAPL'),...
% 	genContract([],'SPOT'),...
% genContract([],'CCI'),...%TELECOMM
% genContract([],'VZ'),...
% genContract([],'T'),...genContract([],'TWTC'),...genContract([],'WIN'),...genContract([],'FTR'),...
% genContract([],'AMGN'),... %BIOTECH
% genContract([],'GILD'),...
% genContract([],'PFE'),... %PHARMA
% genContract([],'BMY'),...
% genContract([],'JNJ'),...
% genContract([],'MRK'),...
% genContract([],'UNM'),...
% genContract([],'LNC'),...
% genContract([],'XOM'),...%ENERGY
% genContract([],'OXY'),...
% genContract([],'HD'),...
% genContract([],'LOW'),...
% genContract([],'GOLD'),...%GOLD
% genContract([],'KGC'),...
% genContract([],'SLV'),... %SILVER ETF
% genContract([],'FB'),... %SOCIAL MEDIA
% genContract([],'TWTR'),...
% genContract([],'YELP'),... %END OF SOCIAL MEDIA
% genContract([],'BTU'),...%COAL MINING
% genContract([],'DAL'),... % TRANSPOT/SHIPPING
% genContract([],'AAL'),...
% genContract([],'FDX'),...
% genContract([],'UPS'),...
% genContract([],'UAL'),...
% genContract([],'AMZN'),...% INTERNET/ECOMMERCE
% genContract([],'SHOP'),...
% genContract([],'NFLX'),...
% genContract([],'IBM'),...
% genContract([],'CSCO'),...
% genContract([],'JNPR'),...genContract([],'SYMC'),...
% genContract([],'BIDU'),...% END OF INTERNET
% genContract([],'INTC'),... %SEMICONDUCTOR
% genContract([],'XLNX'),...
% genContract([],'BAC'),...
% genContract([],'MA'),...
% genContract([],'C'),...
% genContract([],'JPM'),...
% genContract([],'WFC'),...
% genContract([],'V'),...
% genContract([],'KSS'),...
% genContract([],'BBY'),...
% genContract([],'BIG'),...
% genContract([],'TGT'),...
% genContract([],'WMT'),... %END OF RETAIL
% genContract([],'ROKU'),...
% genContract([],'CCL'),...
% genContract([],'DDOG'),...
% genContract([],'DELL'),...
% genContract([],'PTON'),...
% genContract([],'CLDR'),...
% genContract([],'DGLY'),...
% genContract([],'AIM'),...
% genContract([],'ZM'),...
% genContract([],'UBER'),...
% genContract([],'AMD'),...
% genContract([],'TSLA'),...
% genContract([],'NOW'),...
% genContract([],'LITE'),...
% genContract([],'BYND'),...
% genContract([],'MRNA'),...
% genContract([],'NVDA'),...
% genContract([],'DOCU'),...
% genContract([],'F'),...
% genContract([],'GE'),...
% genContract([],'DIS'),...
% genContract([],'EEM'),...
% genContract([],'GOOGL'),...
% genContract([],'KO'),...
% genContract([],'INO'),...
% genContract([],'BABA'),...
% genContract([],'SHIP'),...
% genContract([],'FSLY'),...
% genContract([],'TWLO'),...
% genContract([],'AVGO'),...
% genContract([],'QCOM'),...
% genContract([],'SBUX'),...
% genContract([],'MMM'),...
% genContract([],'ULTA')...S&P500
% };
