ibcontractmanager.DataProvider.Historical={'ib'};
ibcontractmanager.DataProvider.RealTime={'ib'};

contracts={
genContract([],'GOOG','','','SMART'),...
genContract([],'AAPL'),...
genContract([],'AAL'),...
genContract([],'TSLA'),...
genContract([],'NVDA'),...
genContract([],'QQQ'),...
genContract([],'SPY','','','ARCA'),...
genContract([],'XOM'),...%ENERGY
genContract([],'GOLD'),...%GOLD
genContract([],'FB'),... %SOCIAL MEDIA
genContract([],'AMZN'),...% INTERNET/ECOMMERCE
genContract([],'MSFT','MSFT','STK','SMART','NASDAQ'),... % SOFTWARE
genContract([],'IWM','','','ARCA'),...
genContract([],'USO','','','ARCA'),...
genContract([],'GLD','','','ARCA'),...
genContract([],'SLV','','','ARCA')
};

ibcontractmanager.DataProvider.Historical={'ib'};
ibcontractmanager.DataProvider.RealTime={'ib'};

