contracts={...
genContract('TSLA')... EV
genContract('FSR')...
genContract('RIDE')...
genContract('HYLN')...
genContract('XL')...
genContract('GOEV')...
genContract('WKHS')...
genContract('SOLO')...
genContract('IDEX')...
genContract('FUV')...
genContract('AYRO')...
genContract('GP')...
genContract('NKLA')...
genContract('NIO')... EV china
genContract('XPEV')...
genContract('LI')...
genContract('KNDI')...
genContract('BYDDY')...
genContract('NIU')...
genContract('CIIC')... EV SPAC pre-merger
genContract('NGA')...
genContract('GIK')...
genContract('FIII')...
genContract('LAZR')...Lidar
genContract('VLDR')...
genContract('MVIS')...
genContract('CGRO')...SPAC pre mager
genContract('IPV')...
genContract('THBR')...
genContract('CLA')...
genContract('RMO')...battery
genContract('QS')...
genContract('CBAT')...
genContract('THCB')...spac-premarger
genContract('BLNK')...charing
genContract('BEEM')...
genContract('SBE')...spac-premerger
genContract('TPGY')...
genContract('NBAC')...
genContract('CLSK')...enery sources
genContract('EOSE')...
genContract('STPK')...spac-pre-merger
genContract('MP')...natural resources for battery
genContract('WWR')...
genContract('ALB')...
genContract('LTHM')...
genContract('LAC')...
genContract('VALE')...
genContract('PLL')...
genContract('SQM')...
genContract('DRIV')...EV ETF's
genContract('HAIL')...
genContract('IDRV')...
genContract('PBW')...
genContract('EKAR')...
genContract('LIT')...
genContract('ICLN')...
genContract('SEDG')...Solar
genContract('ENPH')...
genContract('FSLR')...
genContract('NEE')...
genContract('RUN')...
genContract('JKS')...
genContract('DQ')...
genContract('MAXN')...
genContract('CSIQ')...
genContract('NOVA')...
genContract('SPWR')...
genContract('SOLOSPI')...
genContract('SUNW')...
genContract('JE')...
genContract('POLA')...
genContract('PPSI')...
genContract('ALAC')...spac premberger
genContract('FCEL')...hydrogen fuel cell
genContract('PLUG')...
genContract('BEEMBLDP')...
genContract('HTOO')...
genContract('AMCI')... spac-premerger
};