function tt=NewTickDataTimeTable()

keySet =   {0,1,2,3,4,5,6,7,8,9 ,22,23,24,25,28,29,30,31};
valueSet = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18];
ticIndexToDataHandler = containers.Map(keySet,valueSet)

vartypes=cell(1,19);
vartypes(:)={'double'};

tt=timetable('Size',[0 18],'VariableNames',...
    {...
    'BidSize','BidPrice','AskPrice','AskSize',...
    'LastPrice','LastSize','High','Low',...
    'Volume','ClosPrice',...
    ...
    'AverageVolume','OpenInterest','OptionHistoricalVolatility',...
    'OptionImpliedVolatility',...
    'OptionCallOpenInterest',...
    'OptionPutOpenInterest','OptionCallVolume','OptionPutVolume'...
    },...
    'VariableTypes',vartypes,...
    'TimeStep',minutes(1) ...
);

vartypes(1)={'datetime'};
t=table('Size',[0 19],'VariableNames',...
    {'Date',...
    'BidSize','BidPrice','AskPrice','AskSize',...
    'LastPrice','LastSize','High','Low',...
    'Volume','ClosPrice',...
    ...
    'AverageVolume','OpenInterest','OptionHistoricalVolatility',...
    'OptionImpliedVolatility',...
    'OptionCallOpenInterest',...
    'OptionPutOpenInterest','OptionCallVolume','OptionPutVolume'...
    },...
    'VariableTypes',vartypes...
);
t(1,:)=table(datetime(),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)


end

%% full list
% tt=timetable('Size',[0 100],'VariableNames',...
%     {...
%     'BidSize','BidPrice','AskPrice','AskSize',...
%     'LastPrice','LastSize','High','Low',...
%     'Volume','ClosPrice','BidOptionComputation','AskOptionComputation',...
%     'LastOptionComputation','ModelOptionComputation','OpenTick','Low13Weeks',...
%     'High13Weeks','Low26Weeks','High26Weeks','Low52Weeks',...
%     'High52Weeks','AverageVolume','OpenInterest','OptionHistoricalVolatility',...
%     'OptionImpliedVolatility','OptionBidExchange','OptionAskExchange','OptionCallOpenInterest',...
%     'OptionPutOpenInterest','OptionCallVolume','OptionPutVolume','IndexFuturePremium',...
%     'BidExchange','AskEXchange','AuctionVolume','AuctionPrice',...
%     'AuctionImbalance','MarkPrice','BidEFPComputation','AskEFPComputation',...
%     'LastEFPComputation','OpenEFPComputation','HighEFPComputation','LowEFPComputation',...
%     'CloseEFPComputation','LastTimestamp','Shortable','RESERVED1',...
%     'RTVolume',... % includes VWAP
%     'Halted','BidYield','AskYield','LastYield',...
%     'CustomOptionComputation','TradeCount','TradeRate','VolumeRate',...
%     'LastRTHTrade','RTHistoricalVolatility','IBDividends','BondFactorMultiplier',...
%     'RegulatoryImbalance','News','ShortTermVolume3Minutes','ShortTermVolume5Minutes',...
%     'ShortTermVolume10Minutes','DelayedBid','DelayedAsk','DelayedLast',...
%     'DelayedBidSize','DelayedAskSize','DelayedLastSize','DelayedhighPrice',...
%     'DelayedLowPrice','DleayedVolume','DelayedClose','DelayedOpen',...
%     'RTTadeVolume','CreditmanMarkPrice','CreditmanSlowMarkPrice','DelayedBidOption',...
%     'DelayedAskOption','DelayedLastOption','DelayedModelOption','LastExchange',...
%     'LastRegulatoryTime','FuturesOpenInterest','AverageOptionVolume','DelayedLastTimestamp',...
%     'ShortableShared','ETFNavClose','ETFNavPriorClose','ETFNavBid',...
%     'ETFNavAsk','ETFNavLast','ETFNavFrozenLast','ETFNavHigh',...
%     'ETFNavLow','','','',...
% });