looperParams.symbols={'AAL','AAPL','AMD','AMZN','BAC','BA','TSLA','GE','WMT','SHOP','MSFT','NVDA','NFLX','DIS','FB','SPY'};
looperParams.runOnce=1;
looperParams.graph.saveFigures=0;
looperParams.graph.show=2; %1 show if signals, 2 always show
looperParams.graph.isfull=1;
looperParams.date=basedate;
looperParams.getdatainit=1;
looperParams.getalldatainrealtime=0;
looperParams.updaterealtime=1;
looperParams.graph.showlimit=390;
looperParams.processlimit=0;
looperParams.doBookOnly=0;
looperParams.backStudyPoints=0;
useparfor=inf;