<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>MHA</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\temp TWS API\source\CSharpClient\client\CSharpAPI.csproj" />
    <ProjectReference Include="..\SystemExtension\SystemExtension.csproj" />
    <ProjectReference Include="..\TickDefinition\TickDefinition.csproj" />
  </ItemGroup>

</Project>
