looperEngine.contracts={genContract([],'AAL'),...
genContract([],'AAPL'),...
genContract([],'AMD'),...
genContract([],'AMZN'),...
genContract([],'BAC'),...
genContract([],'BA'),...
genContract([],'TSLA'),...
genContract([],'BYND'),...
genContract([],'WMT'),...
genContract([],'SHOP'),...
genContract([],'MSFT','MSFT','STK','SMART','NASDAQ'),...
genContract([],'NVDA'),...
genContract([],'NFLX'),...
genContract([],'DIS'),...
genContract([],'FB'),...
genContract([],'SPY')
};
%looperEngine.symbols={'AAL','AAPL','AMD','AMZN','BAC','BA','TSLA','KO','WMT','SHOP','MSFT','NVDA','NFLX','DIS','FB','SPY'};
looperEngine.ui.runOnce=0;
looperEngine.graph.saveFigures=0;
looperEngine.graph.show=2; %1 show if signals, 2 always show
looperEngine.graph.pauseAfterGraph=0;
looperEngine.date=basedate;
looperEngine.data.getdatainit=1;
looperEngine.data.getalldatainrealtime=0;
looperEngine.data.updaterealtime=1;
looperEngine.graph.showlimit=60;
looperEngine.process.limit=0;

useparfor=0;


looperEngine.graph.scalepercent=1.1;